### ISSUE TITLE
Doesn't deal with polygon geometry

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#13]
This site:

http://eric.clst.org/Stuff/USGeoJSON

Has a whole bunch of GeoJSON of US congressional areas and so forth, we don't get much from importing these since all of the action is in the "geometry" tag, we could imagine putting this into a separate table...

Quite a big one here:
http://eric.clst.org/wupl/Stuff/gz_2010_us_outline_500k.json

**Comment by drj11** [comment]
Since the endgoal in my opinion should be to feed into Tableau, do you know how we need to represent areas in order to get the right OData feed to Tableau? I assume it's something like one row per polygon point, or polygon edge, or polygon, but the details matter.

**Comment by scraperdragon** [comment]
http://kb.tableausoftware.com/articles/knowledgebase/polygon-shaded-maps

**Comment by IanHopkinson** [comment]
Fixed
