### ISSUE TITLE
We should have features, points and polygons tables

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#16]
We should potentially put points in a separate table called `points` and rename the `swdata` table `features` with a `feature_index` in each table as a common key. This would make the handling of the different datatypes equivalent but have the downside of making data download more complex - someone just interested in points would have to download two separate files.

**Comment by drj11** [comment]
There are plenty of datasets with 0 points per feature (eg, a polygon based country dataset). Are there any datasets with more than one point per feature? If no, or very few, I would suggest keeping points and features together (in a renamed `feature` table). More practical, but less elegant.

**Comment by IanHopkinson** [comment]
OK - renamed swdata to feature
