### ISSUE TITLE
The tool directory has a tool directory inside it and so forth unto the ends of the universe

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#2]

**Comment by drj11** [comment]
well, yes.

What is the problem? Specifically, did something break, or did you find something confusing?

**Comment by IanHopkinson** [comment]
This strikes me intuitively as a bad thing but I have found no bad consequences for this so far

**Comment by drj11** [comment]
until we have evidence that it's harmful or confusing, I'm closing this.
