### ISSUE TITLE
No warning that the target resource is not of the required format

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#4]
This might be GeoJSON:

http://data.police.uk/api/crimes-street/all-crime?lat=52.629729&lng=-1.131592&date=2011-08

**Comment by drj11** [comment]
It's not.

a) it should be (how do we raise this with data.police.uk?)
b) could easily modify the tool to cope.

I intend to do b) in this case, but where do we draw the line?

**Comment by drj11** [comment]
I've now modified the tool so that it shows Python errors, but at the moment it's just the backtrace, so it's not at all useful (except for programmers).

**Comment by drj11** [comment]
Closing. (since we now get some sort of error).
