### ISSUE TITLE
Import seems to have stalled for this (moderate size) dataset

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#5]
http://opendataserver.ashevillenc.gov/geoserver/ows?service=WFS&request=GetFeature&srsName=EPSG:4326&typeName=coagis:coa_crime_mapper_apd_locations_view&maxFeatures=1000000&outputFormat=json

**Comment by IanHopkinson** [comment]
Gets there in the end but the mapping tool is un-useable with ~9000 datapoints

**Comment by drj11** [comment]
I think we can probably load this a lot faster.

**Comment by drj11** [comment]
Now I've managed to load this dataset, it has 62e3 rows, which is quite a lot for GeoJSON files. The filesize is 28MB. When I tried to view it using the map tool, it crashed with one of chrome sad face pages.

**Comment by drj11** [comment]
lots of points messes up the map tool anyway: https://github.com/scraperwiki/map-tool/issues/14
